# tools
required = [
  "gopkg.in/reform.v1/reform",

  "github.com/vektra/mockery/cmd/mockery",

  # We do not vendor promtool. See https://jira.percona.com/browse/PMM-2182
  # "github.com/prometheus/prometheus/cmd/promtool",

  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
  "github.com/go-swagger/go-swagger/cmd/swagger",
  'github.com/cespare/xxhash'
]

ignored = [
  'github.com/cespare/xxhash/v2'
]

[prune]
  go-tests = true

  # to keep google/api/annotations.proto
  # non-go = true
  # unused-packages = true

[[constraint]]
  # https://jira.percona.com/browse/PMM-1710
  # https://jira.percona.com/browse/PMM-3209
  name = "github.com/percona/kardianos-service"
  branch = "PMM-3209-supervisord-fixes-for-pmm-managed"

[[constraint]]
  # https://jira.percona.com/browse/PMM-1561
  name = "github.com/hashicorp/consul"
  version = "~v1.11.5"

[[constraint]]
  name = 'github.com/cespare/xxhash'
  version = "^2.1.2"

[[override]]
  name = "github.com/shatteredsilicon/promconfig"
  branch = "master"

[[override]]
  name = "github.com/spf13/viper"
  version = "=v1.1.1"

[[override]]
  name = 'github.com/prometheus/client_golang'
  version = "~v1.11.1"

[[override]]
  name = 'github.com/prometheus/client_model'
  version = "~v0.2.0"

[[override]]
  name = 'github.com/prometheus/common'
  version = "~v0.26.0"

[[override]]
  name = "github.com/shatteredsilicon/ssm"
  branch = "1.x"

[[override]]
  name = "github.com/shatteredsilicon/snmp_exporter"
  branch = "ssm-1.x"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  source = "github.com/shatteredsilicon/go-sql-driver-mysql"
  version = "v1.7.1.1"
