// Code generated by go-swagger; DO NOT EDIT.

package r_d_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/shatteredsilicon/ssm-managed/api/swagger/models"
)

// AddMixin6Reader is a Reader for the AddMixin6 structure.
type AddMixin6Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddMixin6Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAddMixin6OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddMixin6OK creates a AddMixin6OK with default headers values
func NewAddMixin6OK() *AddMixin6OK {
	return &AddMixin6OK{}
}

/*AddMixin6OK handles this case with default header values.

(empty)
*/
type AddMixin6OK struct {
	Payload models.APIRDSAddResponse
}

func (o *AddMixin6OK) Error() string {
	return fmt.Sprintf("[POST /v0/rds][%d] addMixin6OK  %+v", 200, o.Payload)
}

func (o *AddMixin6OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
