// Code generated by go-swagger; DO NOT EDIT.

package r_d_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new r d s API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for r d s API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
AddMixin6 add mixin6 API
*/
func (a *Client) AddMixin6(params *AddMixin6Params) (*AddMixin6OK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddMixin6Params()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "AddMixin6",
		Method:             "POST",
		PathPattern:        "/v0/rds",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &AddMixin6Reader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*AddMixin6OK), nil

}

/*
Detail detail API
*/
func (a *Client) Detail(params *DetailParams) (*DetailOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDetailParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Detail",
		Method:             "GET",
		PathPattern:        "/v0/rds/detail",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DetailReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DetailOK), nil

}

/*
Discover discover API
*/
func (a *Client) Discover(params *DiscoverParams) (*DiscoverOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDiscoverParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Discover",
		Method:             "POST",
		PathPattern:        "/v0/rds/discover",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DiscoverReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DiscoverOK), nil

}

/*
ListMixin6 list mixin6 API
*/
func (a *Client) ListMixin6(params *ListMixin6Params) (*ListMixin6OK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListMixin6Params()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "ListMixin6",
		Method:             "GET",
		PathPattern:        "/v0/rds",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListMixin6Reader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListMixin6OK), nil

}

/*
RemoveMixin6 remove mixin6 API
*/
func (a *Client) RemoveMixin6(params *RemoveMixin6Params) (*RemoveMixin6OK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRemoveMixin6Params()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "RemoveMixin6",
		Method:             "DELETE",
		PathPattern:        "/v0/rds",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &RemoveMixin6Reader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*RemoveMixin6OK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
