// Code generated by go-swagger; DO NOT EDIT.

package r_d_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/shatteredsilicon/ssm-managed/api/swagger/models"
)

// NewRemoveMixin6Params creates a new RemoveMixin6Params object
// with the default values initialized.
func NewRemoveMixin6Params() *RemoveMixin6Params {
	var ()
	return &RemoveMixin6Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveMixin6ParamsWithTimeout creates a new RemoveMixin6Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemoveMixin6ParamsWithTimeout(timeout time.Duration) *RemoveMixin6Params {
	var ()
	return &RemoveMixin6Params{

		timeout: timeout,
	}
}

// NewRemoveMixin6ParamsWithContext creates a new RemoveMixin6Params object
// with the default values initialized, and the ability to set a context for a request
func NewRemoveMixin6ParamsWithContext(ctx context.Context) *RemoveMixin6Params {
	var ()
	return &RemoveMixin6Params{

		Context: ctx,
	}
}

// NewRemoveMixin6ParamsWithHTTPClient creates a new RemoveMixin6Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRemoveMixin6ParamsWithHTTPClient(client *http.Client) *RemoveMixin6Params {
	var ()
	return &RemoveMixin6Params{
		HTTPClient: client,
	}
}

/*RemoveMixin6Params contains all the parameters to send to the API endpoint
for the remove mixin6 operation typically these are written to a http.Request
*/
type RemoveMixin6Params struct {

	/*Body*/
	Body *models.APIRDSRemoveRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the remove mixin6 params
func (o *RemoveMixin6Params) WithTimeout(timeout time.Duration) *RemoveMixin6Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove mixin6 params
func (o *RemoveMixin6Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove mixin6 params
func (o *RemoveMixin6Params) WithContext(ctx context.Context) *RemoveMixin6Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove mixin6 params
func (o *RemoveMixin6Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove mixin6 params
func (o *RemoveMixin6Params) WithHTTPClient(client *http.Client) *RemoveMixin6Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove mixin6 params
func (o *RemoveMixin6Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the remove mixin6 params
func (o *RemoveMixin6Params) WithBody(body *models.APIRDSRemoveRequest) *RemoveMixin6Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the remove mixin6 params
func (o *RemoveMixin6Params) SetBody(body *models.APIRDSRemoveRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveMixin6Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
