// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeRemoveRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeRemoveRequest) Reset()         { *m = NodeRemoveRequest{} }
func (m *NodeRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*NodeRemoveRequest) ProtoMessage()    {}
func (*NodeRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_5622b8ba937ff7b4, []int{0}
}
func (m *NodeRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRemoveRequest.Unmarshal(m, b)
}
func (m *NodeRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRemoveRequest.Marshal(b, m, deterministic)
}
func (dst *NodeRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRemoveRequest.Merge(dst, src)
}
func (m *NodeRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_NodeRemoveRequest.Size(m)
}
func (m *NodeRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRemoveRequest proto.InternalMessageInfo

func (m *NodeRemoveRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NodeRemoveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeRemoveResponse) Reset()         { *m = NodeRemoveResponse{} }
func (m *NodeRemoveResponse) String() string { return proto.CompactTextString(m) }
func (*NodeRemoveResponse) ProtoMessage()    {}
func (*NodeRemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_5622b8ba937ff7b4, []int{1}
}
func (m *NodeRemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRemoveResponse.Unmarshal(m, b)
}
func (m *NodeRemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRemoveResponse.Marshal(b, m, deterministic)
}
func (dst *NodeRemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRemoveResponse.Merge(dst, src)
}
func (m *NodeRemoveResponse) XXX_Size() int {
	return xxx_messageInfo_NodeRemoveResponse.Size(m)
}
func (m *NodeRemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRemoveResponse proto.InternalMessageInfo

type NodeListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeListRequest) Reset()         { *m = NodeListRequest{} }
func (m *NodeListRequest) String() string { return proto.CompactTextString(m) }
func (*NodeListRequest) ProtoMessage()    {}
func (*NodeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_5622b8ba937ff7b4, []int{2}
}
func (m *NodeListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeListRequest.Unmarshal(m, b)
}
func (m *NodeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeListRequest.Marshal(b, m, deterministic)
}
func (dst *NodeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeListRequest.Merge(dst, src)
}
func (m *NodeListRequest) XXX_Size() int {
	return xxx_messageInfo_NodeListRequest.Size(m)
}
func (m *NodeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeListRequest proto.InternalMessageInfo

type NodeInstanceService struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Port                 uint32   `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Engine               string   `protobuf:"bytes,6,opt,name=engine,proto3" json:"engine,omitempty"`
	EngineVersion        string   `protobuf:"bytes,7,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInstanceService) Reset()         { *m = NodeInstanceService{} }
func (m *NodeInstanceService) String() string { return proto.CompactTextString(m) }
func (*NodeInstanceService) ProtoMessage()    {}
func (*NodeInstanceService) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_5622b8ba937ff7b4, []int{3}
}
func (m *NodeInstanceService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInstanceService.Unmarshal(m, b)
}
func (m *NodeInstanceService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInstanceService.Marshal(b, m, deterministic)
}
func (dst *NodeInstanceService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInstanceService.Merge(dst, src)
}
func (m *NodeInstanceService) XXX_Size() int {
	return xxx_messageInfo_NodeInstanceService.Size(m)
}
func (m *NodeInstanceService) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInstanceService.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInstanceService proto.InternalMessageInfo

func (m *NodeInstanceService) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NodeInstanceService) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NodeInstanceService) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *NodeInstanceService) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NodeInstanceService) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *NodeInstanceService) GetEngine() string {
	if m != nil {
		return m.Engine
	}
	return ""
}

func (m *NodeInstanceService) GetEngineVersion() string {
	if m != nil {
		return m.EngineVersion
	}
	return ""
}

type NodeInstance struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Services             []*NodeInstanceService `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *NodeInstance) Reset()         { *m = NodeInstance{} }
func (m *NodeInstance) String() string { return proto.CompactTextString(m) }
func (*NodeInstance) ProtoMessage()    {}
func (*NodeInstance) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_5622b8ba937ff7b4, []int{4}
}
func (m *NodeInstance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInstance.Unmarshal(m, b)
}
func (m *NodeInstance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInstance.Marshal(b, m, deterministic)
}
func (dst *NodeInstance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInstance.Merge(dst, src)
}
func (m *NodeInstance) XXX_Size() int {
	return xxx_messageInfo_NodeInstance.Size(m)
}
func (m *NodeInstance) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInstance.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInstance proto.InternalMessageInfo

func (m *NodeInstance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeInstance) GetServices() []*NodeInstanceService {
	if m != nil {
		return m.Services
	}
	return nil
}

type NodeListResponse struct {
	Instances            []*NodeInstance `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NodeListResponse) Reset()         { *m = NodeListResponse{} }
func (m *NodeListResponse) String() string { return proto.CompactTextString(m) }
func (*NodeListResponse) ProtoMessage()    {}
func (*NodeListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_5622b8ba937ff7b4, []int{5}
}
func (m *NodeListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeListResponse.Unmarshal(m, b)
}
func (m *NodeListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeListResponse.Marshal(b, m, deterministic)
}
func (dst *NodeListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeListResponse.Merge(dst, src)
}
func (m *NodeListResponse) XXX_Size() int {
	return xxx_messageInfo_NodeListResponse.Size(m)
}
func (m *NodeListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeListResponse proto.InternalMessageInfo

func (m *NodeListResponse) GetInstances() []*NodeInstance {
	if m != nil {
		return m.Instances
	}
	return nil
}

type NodeRemoveServiceRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeRemoveServiceRequest) Reset()         { *m = NodeRemoveServiceRequest{} }
func (m *NodeRemoveServiceRequest) String() string { return proto.CompactTextString(m) }
func (*NodeRemoveServiceRequest) ProtoMessage()    {}
func (*NodeRemoveServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_5622b8ba937ff7b4, []int{6}
}
func (m *NodeRemoveServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRemoveServiceRequest.Unmarshal(m, b)
}
func (m *NodeRemoveServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRemoveServiceRequest.Marshal(b, m, deterministic)
}
func (dst *NodeRemoveServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRemoveServiceRequest.Merge(dst, src)
}
func (m *NodeRemoveServiceRequest) XXX_Size() int {
	return xxx_messageInfo_NodeRemoveServiceRequest.Size(m)
}
func (m *NodeRemoveServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRemoveServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRemoveServiceRequest proto.InternalMessageInfo

func (m *NodeRemoveServiceRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NodeRemoveServiceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeRemoveServiceRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type NodeRemoveServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeRemoveServiceResponse) Reset()         { *m = NodeRemoveServiceResponse{} }
func (m *NodeRemoveServiceResponse) String() string { return proto.CompactTextString(m) }
func (*NodeRemoveServiceResponse) ProtoMessage()    {}
func (*NodeRemoveServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_5622b8ba937ff7b4, []int{7}
}
func (m *NodeRemoveServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRemoveServiceResponse.Unmarshal(m, b)
}
func (m *NodeRemoveServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRemoveServiceResponse.Marshal(b, m, deterministic)
}
func (dst *NodeRemoveServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRemoveServiceResponse.Merge(dst, src)
}
func (m *NodeRemoveServiceResponse) XXX_Size() int {
	return xxx_messageInfo_NodeRemoveServiceResponse.Size(m)
}
func (m *NodeRemoveServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRemoveServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRemoveServiceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*NodeRemoveRequest)(nil), "api.NodeRemoveRequest")
	proto.RegisterType((*NodeRemoveResponse)(nil), "api.NodeRemoveResponse")
	proto.RegisterType((*NodeListRequest)(nil), "api.NodeListRequest")
	proto.RegisterType((*NodeInstanceService)(nil), "api.NodeInstanceService")
	proto.RegisterType((*NodeInstance)(nil), "api.NodeInstance")
	proto.RegisterType((*NodeListResponse)(nil), "api.NodeListResponse")
	proto.RegisterType((*NodeRemoveServiceRequest)(nil), "api.NodeRemoveServiceRequest")
	proto.RegisterType((*NodeRemoveServiceResponse)(nil), "api.NodeRemoveServiceResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeClient interface {
	Remove(ctx context.Context, in *NodeRemoveRequest, opts ...grpc.CallOption) (*NodeRemoveResponse, error)
	List(ctx context.Context, in *NodeListRequest, opts ...grpc.CallOption) (*NodeListResponse, error)
	RemoveService(ctx context.Context, in *NodeRemoveServiceRequest, opts ...grpc.CallOption) (*NodeRemoveServiceResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Remove(ctx context.Context, in *NodeRemoveRequest, opts ...grpc.CallOption) (*NodeRemoveResponse, error) {
	out := new(NodeRemoveResponse)
	err := c.cc.Invoke(ctx, "/api.Node/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) List(ctx context.Context, in *NodeListRequest, opts ...grpc.CallOption) (*NodeListResponse, error) {
	out := new(NodeListResponse)
	err := c.cc.Invoke(ctx, "/api.Node/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) RemoveService(ctx context.Context, in *NodeRemoveServiceRequest, opts ...grpc.CallOption) (*NodeRemoveServiceResponse, error) {
	out := new(NodeRemoveServiceResponse)
	err := c.cc.Invoke(ctx, "/api.Node/RemoveService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
type NodeServer interface {
	Remove(context.Context, *NodeRemoveRequest) (*NodeRemoveResponse, error)
	List(context.Context, *NodeListRequest) (*NodeListResponse, error)
	RemoveService(context.Context, *NodeRemoveServiceRequest) (*NodeRemoveServiceResponse, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Remove(ctx, req.(*NodeRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).List(ctx, req.(*NodeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_RemoveService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRemoveServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).RemoveService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/RemoveService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).RemoveService(ctx, req.(*NodeRemoveServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Remove",
			Handler:    _Node_Remove_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Node_List_Handler,
		},
		{
			MethodName: "RemoveService",
			Handler:    _Node_RemoveService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node.proto",
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_node_5622b8ba937ff7b4) }

var fileDescriptor_node_5622b8ba937ff7b4 = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0x56, 0xb2, 0xcb, 0x96, 0x9d, 0xb2, 0xa5, 0x3b, 0x94, 0xe2, 0x06, 0xa8, 0x2a, 0x0b, 0x44,
	0xb5, 0x87, 0x0d, 0x2a, 0x9c, 0xb8, 0x22, 0x21, 0x21, 0x21, 0x0e, 0xa9, 0x84, 0xb8, 0x21, 0xd3,
	0x8c, 0x22, 0x4b, 0xd4, 0x0e, 0xb1, 0x89, 0x84, 0x10, 0x17, 0x5e, 0x81, 0x13, 0x2f, 0xc3, 0x4b,
	0xf0, 0x0a, 0x3c, 0x08, 0xb2, 0x9d, 0xbf, 0xdd, 0x0d, 0xb7, 0xf1, 0x37, 0xe3, 0xef, 0xfb, 0xf2,
	0x79, 0x02, 0xa0, 0x74, 0x4e, 0xeb, 0xb2, 0xd2, 0x56, 0xe3, 0x44, 0x94, 0x32, 0x79, 0x50, 0x68,
	0x5d, 0x7c, 0xa2, 0x54, 0x94, 0x32, 0x15, 0x4a, 0x69, 0x2b, 0xac, 0xd4, 0xca, 0x84, 0x11, 0xfe,
	0x04, 0x96, 0x6f, 0x75, 0x4e, 0x19, 0x5d, 0xeb, 0x9a, 0x32, 0xfa, 0xfc, 0x85, 0x8c, 0x45, 0x84,
	0xa9, 0x12, 0xd7, 0xc4, 0xa2, 0xb3, 0xe8, 0x7c, 0x9e, 0xf9, 0x9a, 0x1f, 0x01, 0x0e, 0x07, 0x4d,
	0xa9, 0x95, 0x21, 0xbe, 0x84, 0xdb, 0x0e, 0x7d, 0x23, 0x8d, 0x6d, 0x2e, 0xf3, 0xdf, 0x11, 0xdc,
	0x71, 0xd8, 0x6b, 0x65, 0xac, 0x50, 0x57, 0x74, 0x49, 0x55, 0x2d, 0xaf, 0x08, 0x0f, 0x20, 0x96,
	0xb9, 0xa7, 0x5c, 0x64, 0xb1, 0xcc, 0x9d, 0x88, 0xfd, 0x5a, 0x12, 0x8b, 0x83, 0x88, 0xab, 0xf1,
	0x18, 0x66, 0x15, 0x15, 0x52, 0x2b, 0x36, 0xf1, 0x68, 0x73, 0x42, 0x06, 0x7b, 0x22, 0xcf, 0x2b,
	0x32, 0x86, 0x4d, 0x7d, 0xa3, 0x3d, 0x3a, 0x96, 0x52, 0x57, 0x96, 0xdd, 0xf0, 0xbc, 0xbe, 0x76,
	0x2c, 0xa4, 0x0a, 0xa9, 0x88, 0xcd, 0x02, 0x4b, 0x38, 0xe1, 0x63, 0x38, 0x08, 0xd5, 0x87, 0x9a,
	0x2a, 0xe3, 0x54, 0xf6, 0x7c, 0x7f, 0x11, 0xd0, 0x77, 0x01, 0xe4, 0xef, 0xe1, 0xd6, 0xd0, 0xff,
	0x58, 0x1a, 0xf8, 0x1c, 0x6e, 0x9a, 0xf0, 0x5d, 0x86, 0xc5, 0x67, 0x93, 0xf3, 0xfd, 0x0b, 0xb6,
	0x16, 0xa5, 0x5c, 0x8f, 0x7c, 0x78, 0xd6, 0x4d, 0xf2, 0x97, 0x70, 0xd8, 0xa7, 0x15, 0x12, 0xc4,
	0x14, 0xe6, 0xb2, 0xb9, 0x60, 0x58, 0xe4, 0xa9, 0x96, 0x3b, 0x54, 0x59, 0x3f, 0xc3, 0x33, 0x60,
	0xfd, 0x43, 0xb4, 0x1a, 0xcd, 0xc3, 0x8d, 0x64, 0xec, 0xad, 0xc7, 0x03, 0xeb, 0x6d, 0xee, 0x93,
	0x3e, 0x77, 0x7e, 0x1f, 0x4e, 0x46, 0x38, 0x83, 0xc3, 0x8b, 0x5f, 0x31, 0x4c, 0x5d, 0x17, 0x2f,
	0x61, 0x16, 0x26, 0xf0, 0xb8, 0x73, 0xb8, 0xb1, 0x38, 0xc9, 0xbd, 0x1d, 0xbc, 0xd9, 0x13, 0xf6,
	0xe3, 0xcf, 0xdf, 0x9f, 0x31, 0xae, 0x0e, 0xd3, 0xfa, 0x69, 0xea, 0x36, 0xd4, 0xa4, 0xdf, 0x9c,
	0x9b, 0xef, 0xf8, 0x0a, 0xa6, 0x2e, 0x0f, 0x3c, 0xea, 0xae, 0x0e, 0x96, 0x29, 0xb9, 0xbb, 0x85,
	0xb6, 0x6b, 0xe7, 0xe9, 0xf6, 0x71, 0xde, 0xd1, 0xa1, 0x85, 0xc5, 0x86, 0x7d, 0x7c, 0xb8, 0xe5,
	0x65, 0x33, 0xaa, 0xe4, 0xf4, 0x7f, 0xed, 0x46, 0xe2, 0x91, 0x97, 0x38, 0x5d, 0x9d, 0x6c, 0x3b,
	0x4e, 0xdb, 0xe7, 0x7c, 0x11, 0xad, 0x3e, 0xce, 0xfc, 0x5f, 0xf4, 0xec, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa4, 0xd7, 0xb0, 0xc1, 0x76, 0x03, 0x00, 0x00,
}
