// Code generated by go-swagger; DO NOT EDIT.

package scrape_configs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListMixin8Params creates a new ListMixin8Params object
// with the default values initialized.
func NewListMixin8Params() *ListMixin8Params {

	return &ListMixin8Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewListMixin8ParamsWithTimeout creates a new ListMixin8Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewListMixin8ParamsWithTimeout(timeout time.Duration) *ListMixin8Params {

	return &ListMixin8Params{

		timeout: timeout,
	}
}

// NewListMixin8ParamsWithContext creates a new ListMixin8Params object
// with the default values initialized, and the ability to set a context for a request
func NewListMixin8ParamsWithContext(ctx context.Context) *ListMixin8Params {

	return &ListMixin8Params{

		Context: ctx,
	}
}

// NewListMixin8ParamsWithHTTPClient creates a new ListMixin8Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListMixin8ParamsWithHTTPClient(client *http.Client) *ListMixin8Params {

	return &ListMixin8Params{
		HTTPClient: client,
	}
}

/*ListMixin8Params contains all the parameters to send to the API endpoint
for the list mixin8 operation typically these are written to a http.Request
*/
type ListMixin8Params struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list mixin8 params
func (o *ListMixin8Params) WithTimeout(timeout time.Duration) *ListMixin8Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list mixin8 params
func (o *ListMixin8Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list mixin8 params
func (o *ListMixin8Params) WithContext(ctx context.Context) *ListMixin8Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list mixin8 params
func (o *ListMixin8Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list mixin8 params
func (o *ListMixin8Params) WithHTTPClient(client *http.Client) *ListMixin8Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list mixin8 params
func (o *ListMixin8Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListMixin8Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
